### ISSUE TITLE
Get rid of *A (with arguments) functions

### ISSUE THREAD

**Issue by belka-ew** [caraus-ecms/graphql#23]
- `objectA`
- `wrappedObjectA`
- `scalarA`
- `wrappedScalarA`

They create unneeded duplication and encourage to write partial functions, so every resolver requires an additional line which is always the same:

```haskell
droid :: MonadIO m => Schema.Resolver m
droid = Schema.objectA "droid" $ \case
   [Schema.Argument "id" (Schema.String i)] -> character =<< liftIO (getDroid i)
   _ -> ActionT $ throwE "Invalid arguments."
```

There should be a better way to handle this. Resolver arguments could be passed:
- Explicitely in a data structure which allows lookups by index or name
- Implicitely in a reader that checks whether the argument exists and throws an exception if not.

**Comment by belka-ew** [comment]
It is even worse. Arguments in GraphQL are not ordered, so a query can provide the arguments in any order, they are distinguished by name. But the resolvers expect the arguments in a specific order, which makes valid queries fail.

It is a big breaking change and I'm not sure there is a sane migration path, but the current behaviour is just wrong.

**Comment by Hazelfire** [comment]
Hey! I totally agree with the order of parameters. This is an issue that I'm facing with using this library.

I would honestly love if we could implement this via a reader monad, because I think the natural way to handle inputs (as I've been doing with my code) is to define a typeclasses (like FromGraphQLInput) that maps between Haskell types and arguments. If we use a reader monad, we could probably achieve a similar type of applicative syntax that is used in FromJSON from aeson. That way, the resolving functions with input can infer what arguments are required and the library can do all the argument validation itself.

I'm not sure if this is what you have in mind? Only problem with this approach is that although it might make the library interface very clean, it might add a bit of complexity to implement. I'd be very interested in trying this out though.

**Comment by belka-ew** [comment]
> I'm not sure if this is what you have in mind?

Exactly.

A reader provides a bit more freedom. I think I can provide a helper function that validates that the argument exists, so the use doesn't have to check `Maybe` manually. And a typeclass can provide automatic conversion as you say. Complexity is not a problem as long as the complexity is maintainable; everythign I want is full spec conformity :)

**Comment by belka-ew** [comment]
This issue is actually solved. Supporting `ToGraphQL`/`FromGraphQL` typeclasses  is a separate issue, I need to thank about on another day.
