### ISSUE TITLE
Cannot parse operations with multiple required arguments.

### ISSUE THREAD

**Issue by Hazelfire** [caraus-ecms/graphql#25]
I'm new to this library, forgive me if I've made a mistake.

When making the following query:
```
mutation auth($username: String!, $password: String){ test }
```

It returns the following syntax parsing error:
```
unexpected ',' expecting '$', ')', or '='
```
pointing to the location of that first comma. I'm expecting this to parse because it is valid GraphQL Syntax.

This only happens when the first parameter is required. The following will parse successfully

```
mutation auth($username: String,$password: String){ test }
```
And so does this even though it has incorrect syntax
```
mutation auth($username: String!$password: String){ test }
```

This bug exists on 0.5.0.1, 0.5.1.0 and the current head (7b92e5bcfded2a592b9be25d0865d26320421570)

I'll look into a solution for this.

**Comment by belka-ew** [comment]
Thanks for an extensive bug report!

> And so does this even though it has incorrect syntax
> `mutation auth($username: String!$password: String){ test }`

It is valid syntax. In GraphQL the commas, like whitespaces, are semantically meaningless   [2.1.5 Insignificant Commas](https://graphql.github.io/graphql-spec/June2018/#sec-Insignificant-Commas). They can be used to separate tokens, but here such separation isn't needed since a type can't contain `$`, so the parser knows where the next token begins.
You can try a query like:
```graphql
query($last: Int!$skip: Int!) {
  allPersons(last: $last, skip: $skip) {
    name
  }
}
```
here: https://www.graphqlbin.com/v2/6RQ6TM
